---
apiVersion: v1
kind: Service
metadata:
  name: weather-forecast-api
  labels:
    app: weather-forecast-api
    color: blue # Change here to switch
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  # We match both the app and the color 
  selector:
    app: weather-forecast-api
    color: blue # Change here to switch
  type: NodePort # Change to 'ClusterIP' if using Ingress
