services:
  app:
    image: weather-forecast-api
    container_name: weather-forecast-api
    build:
      context: src
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 80:80
