version: '3.4'
services:
  app:
    image: demo
    container_name: demo
    build:
      context: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - 80
      - 443
