---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-forecast-api
  labels:
    app: weather-forecast-api
spec:
  selector:
    matchLabels:
      app: weather-forecast-api
  replicas: 2
  template:
    metadata:
      labels:
        app: weather-forecast-api
      # https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus#scraping-pod-metrics-via-annotations
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "80"
    spec:
     containers:
     - name: weather-forecast-api
       image: "minikube/weather-forecast-api:latest"
       imagePullPolicy: Never
       ports:
         - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: weather-forecast-api
  labels:
    app: weather-forecast-api
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: weather-forecast-api
  type: NodePort # ClusterIP
