version: '3.4'
services:
  app:
    image: weather-forecast-api
    container_name: weather-forecast-api
    restart: unless-stopped
    build:
      context: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - VERSION=${TAG}
    ports:
      - 80:80
