version: '3.4'
services:
  app:
    image: ghcr.io/atrakic/weather-forecast-api:main
    container_name: weather-forecast-api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - VERSION=${TAG}
    ports:
      - 8080:80
